#!/usr/bin/env node
'use strict';
const assert = require('assert'); const fs = require('fs'); const os = require('os'); const path = require('path');
const serviceModule = require('../Beocreate2/beo-extensions/signal-flow/routing-service');
const controllerModule = require('../Beocreate2/beo-extensions/signal-flow/routing-controller');
const configurationBackup = require('../Beocreate2/beo-system/configuration-backup');
const root = fs.mkdtempSync(path.join(os.tmpdir(), 'speakerlab-merge-'));
try {
  const service = serviceModule.createService({dataDirectory: root, clock: function() { return new Date('2026-08-10T12:00:00.000Z'); }});
  let configuration = service.state({}).configuration;
  function imported(text, filename, type) {
    const preview = service.measurementPreview(text, filename);
    const result = service.measurementDraft(configuration, 'import', {token: preview.token, type});
    configuration = result.configuration; return result.measurementId;
  }
  const lowID = imported('# FRD\n20 64\n80 70\n160 74\n320 77\n640 80\n1280 83\n2560 86', 'near.frd', 'nearfield');
  const highID = imported('# FRD\n160 80\n320 83\n640 86\n1280 89\n2560 92\n5120 95\n10240 98', 'far.frd', 'farfield');
  const lowBefore = JSON.stringify(configuration.measurements.measurements.find(function(item) { return item.id === lowID; }));
  const preview = service.measurementMergePreview(configuration, {lowSourceId: lowID, highSourceId: highID, mergeFrequencyHz: 640, transitionWidthOctaves: 1, magnitudeOffsetDb: 6, name: 'Merged reference'});
  assert.strictEqual(preview.validation.valid, true); assert.strictEqual(preview.result.phaseAvailable, false); assert.ok(preview.suggestedAlignment.suggestedOffsetDb);
  const sent = [];
  const controller = controllerModule.createController({service, send: function(header, content) { sent.push({header, content}); }});
  controller.handle({header: 'previewMeasurementMerge', content: {configuration, lowSourceId: lowID, highSourceId: highID, mergeFrequencyHz: 640, transitionWidthOctaves: 1, magnitudeOffsetDb: 6}});
  assert.strictEqual(sent.pop().header, 'measurementMergePreview');
  controller.handle({header: 'saveMeasurementMerge', content: Object.assign({configuration}, preview.recipe)});
  assert.strictEqual(sent.pop().header, 'measurementDraft');
  const saved = service.saveMeasurementMerge(configuration, preview.recipe); configuration = saved.configuration;
  const derived = configuration.measurements.measurements.find(function(item) { return item.id === saved.measurementId; });
  assert.strictEqual(derived.type, 'derived-merged-response'); assert.strictEqual(derived.mergeRecipe.lowSourceId, lowID);
  assert.deepStrictEqual(derived.provenance.validFrequencyRangeHz, {minimum: 20, maximum: 10240});
  const secondPreview = service.measurementMergePreview(configuration, {lowSourceId: lowID, highSourceId: highID, mergeFrequencyHz: 640, transitionWidthOctaves: 1, magnitudeOffsetDb: 6});
  assert.notStrictEqual(secondPreview.recipe.resultMeasurementId, derived.id);
  const renamed = service.measurementDraft(configuration, 'update', {measurementId: lowID, name: 'Renamed nearfield source'});
  assert.strictEqual(renamed.validation.valid, true); assert.strictEqual(renamed.configuration.measurements.measurements.find(function(item) { return item.id === derived.id; }).mergeRecipe.lowSourceId, lowID);
  assert.strictEqual(JSON.stringify(configuration.measurements.measurements.find(function(item) { return item.id === lowID; })), lowBefore);
  assert.throws(function() { service.measurementDraft(configuration, 'remove', {measurementId: lowID}); }, function(error) { return error.code === 'MEASUREMENT_HAS_DEPENDENT_MERGE'; });
  const edited = service.saveMeasurementMerge(configuration, Object.assign({}, derived.mergeRecipe, {magnitudeOffsetDb: 5, name: 'Edited merge'}));
  assert.strictEqual(edited.configuration.measurements.measurements.length, 3); assert.strictEqual(edited.configuration.measurements.measurements.find(function(item) { return item.id === derived.id; }).name, 'Edited merge');
  assert.strictEqual(service.save(edited.configuration, null).verified, true);
  assert.strictEqual(service.state({}).configuration.measurements.measurements.find(function(item) { return item.id === derived.id; }).mergeRecipe.magnitudeOffsetDb, 5);
  const backupService = configurationBackup.createConfigurationService({dataDirectory: root, systemVersion: 'test', systemConfiguration: {cardType: 'Beocreate 4-Channel Amplifier'}, clock: function() { return new Date('2026-08-10T12:00:00.000Z'); }});
  const backup = backupService.serializeBackup();
  assert.ok(backup.includes('org.speakerlab.measurement-merge'));
  const backupData = JSON.parse(backup).configuration.settings.items.find(function(item) { return item.name === 'signal-flow.json'; }).data;
  const backedUpDerived = backupData.measurements.measurements.find(function(item) { return item.id === derived.id; });
  assert.strictEqual(backedUpDerived.mergeRecipe.lowSourceHash, backupData.measurements.measurements.find(function(item) { return item.id === lowID; }).integrity.hash);
  assert.strictEqual(backedUpDerived.integrity.hash, edited.configuration.measurements.measurements.find(function(item) { return item.id === derived.id; }).integrity.hash);
  const missingSource = JSON.parse(JSON.stringify(edited.configuration));
  missingSource.measurements.measurements = missingSource.measurements.measurements.filter(function(item) { return item.id !== lowID; });
  assert.ok(service.validate(missingSource).errors.some(function(item) { return item.code === 'MISSING_MERGE_SOURCE'; }));
  fs.writeFileSync(path.join(root, 'signal-flow.json'), JSON.stringify(missingSource));
  assert.throws(function() { backupService.collectBackup(); }, function(error) { return error.code === 'INVALID_SIGNAL_FLOW_CONFIGURATION'; });
  const corruptDerived = JSON.parse(JSON.stringify(edited.configuration));
  corruptDerived.measurements.measurements.find(function(item) { return item.id === derived.id; }).points[0].magnitudeDb += 1;
  assert.ok(service.validate(corruptDerived).errors.some(function(item) { return item.code === 'INTEGRITY_MISMATCH'; }));
  fs.writeFileSync(path.join(root, 'signal-flow.json'), JSON.stringify(corruptDerived));
  assert.throws(function() { backupService.collectBackup(); }, function(error) { return error.code === 'INVALID_SIGNAL_FLOW_CONFIGURATION'; });
  const altered = JSON.parse(JSON.stringify(edited.configuration));
  altered.measurements.measurements = altered.measurements.measurements.filter(function(item) { return item.id !== derived.id; });
  fs.writeFileSync(path.join(root, 'signal-flow.json'), JSON.stringify(altered));
  const restorePreview = backupService.preview(backup);
  assert.ok(restorePreview.plan.replace.includes('settings/signal-flow.json'));
  const restore = backupService.restore(restorePreview.token);
  assert.strictEqual(restore.status, 'success');
  const restored = JSON.parse(fs.readFileSync(path.join(root, 'signal-flow.json'), 'utf8'));
  const restoredDerived = restored.measurements.measurements.find(function(item) { return item.id === derived.id; });
  assert.strictEqual(restoredDerived.mergeRecipe.magnitudeOffsetDb, 5);
  assert.strictEqual(restoredDerived.integrity.hash, backedUpDerived.integrity.hash);
  assert.strictEqual(restored.measurements.measurements.find(function(item) { return item.id === lowID; }).integrity.hash, backedUpDerived.mergeRecipe.lowSourceHash);
  console.log('ok - merge preview, immutable sources, dependency blocking, edit, persistence and backup round trip');
} finally { fs.rmSync(root, {recursive: true, force: true}); }
